version: "3"

services:
  sonarqube:
    image: sonarqube:9.0.1-community
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://127.0.0.1:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      #sonar.search.javaAdditionalOpts: -Dnode.store.allow_mmapfs=false
      sonar.search.javaAdditionalOpts: -Dnode.store.allow_mmap=false
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/qrpoint-sonarqube
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/qrpoint-sonarqube
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
        
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  script:
  postgresql:
#    driver_opts:
#       # Filesystem configuration
#       backup_policy: ENABLED
#       lifecycle_policy: AFTER_14_DAYS
#       performance_mode: maxIO
#       throughput_mode: provisioned
#       provisioned_throughput: 1
  postgresql_data:
#    driver_opts:
#       # Filesystem configuration
#       backup_policy: ENABLED
#       lifecycle_policy: AFTER_14_DAYS
#       performance_mode: maxIO
#       throughput_mode: provisioned
#       provisioned_throughput: 1