FROM sonarqube:9.0.1-community
ENV SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
ENV SONAR_JDBC_USERNAME=sonar
ENV SONAR_JDBC_PASSWORD=sonar
VOLUME /sonarqube_data /opt/sonarqube/data
VOLUME /sonarqube_extensions /opt/sonarqube/extensions
VOLUME /sonarqube_logs /opt/sonarqube/logs
EXPOSE 9000